/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: riach (https://sketchfab.com/riach)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/cyberpunk-room-flooring-dd1af76d296441c7ae6bbb48696e7a9b
Title: Cyberpunk Room Flooring
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['Box001_Material_#44_0']: THREE.Mesh
  }
  materials: {
    Material_44: THREE.MeshPhysicalMaterial
  }
}

export function Floor(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/cyberpunk_room_flooring.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Box001_Material_#44_0'].geometry}
        material={materials.Material_44}
        position={[3.562, 0, 0.765]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Box001_Material_#44_0'].geometry}
        material={materials.Material_44}
        position={[-30, 0, 0.765]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.01, 0.01, 0.01]}
      />
    </group>
  )
}

useGLTF.preload('/cyberpunk_room_flooring.glb')
