/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: assetfactory (https://sketchfab.com/assetfactory)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/post-apocalyptic-fridge-a2fddb529d944c47beb3ab823aa0f7f8
Title: Post apocalyptic fridge
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube_Fridge_0: THREE.Mesh
    Cube001_Fridge_0: THREE.Mesh
    Cylinder_Fridge_0: THREE.Mesh
    Cube004_Fridge_0: THREE.Mesh
    Cube002_Fridge_0: THREE.Mesh
    Cube006_Fridge_0: THREE.Mesh
    Cylinder001_Fridge_0: THREE.Mesh
    Cube005_Fridge_0: THREE.Mesh
    Cube007_Fridge_0: THREE.Mesh
    Cube008_Fridge_0: THREE.Mesh
    Cube009_Fridge_0: THREE.Mesh
    Cube003_Fridge_0: THREE.Mesh
    Cylinder002_Can_0: THREE.Mesh
    Plane_Can_0: THREE.Mesh
    Cylinder006_Can_0: THREE.Mesh
    Plane004_Can_0: THREE.Mesh
    Cylinder004_Can_0: THREE.Mesh
    Plane001_Can_0: THREE.Mesh
    Cylinder003_Can_0: THREE.Mesh
    Plane002_Can_0: THREE.Mesh
  }
  materials: {
    Fridge: THREE.MeshStandardMaterial
    material: THREE.MeshStandardMaterial
  }
}

export function Fridge(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/post_apo_fridge/scene.gltf') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_Fridge_0.geometry}
          material={materials.Fridge}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_Fridge_0.geometry}
          material={materials.Fridge}
          position={[192.659, 259.742, 353.505]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_Fridge_0.geometry}
          material={materials.Fridge}
          position={[144.849, 335.427, 109.058]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_Fridge_0.geometry}
          material={materials.Fridge}
          position={[0, 87.277, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube002_Fridge_0.geometry}
          material={materials.Fridge}
          position={[0, 56.511, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube006_Fridge_0.geometry}
          material={materials.Fridge}
          position={[-128.687, 259.773, 101.887]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001_Fridge_0.geometry}
          material={materials.Fridge}
          position={[133.561, 202.736, 109.025]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube005_Fridge_0.geometry}
          material={materials.Fridge}
          position={[164.241, 17.93, 253.907]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube007_Fridge_0.geometry}
          material={materials.Fridge}
          position={[164.241, -136.414, 253.907]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube008_Fridge_0.geometry}
          material={materials.Fridge}
          position={[164.241, 98.869, 250.125]}
          rotation={[-1.546, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube009_Fridge_0.geometry}
          material={materials.Fridge}
          position={[164.241, 184.247, 253.907]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003_Fridge_0.geometry}
          material={materials.Fridge}
          position={[170.998, 358.615, 249.957]}
          rotation={[-1.596, 0.328, 0.077]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder002_Can_0.geometry}
          material={materials.material}
          position={[-67.289, 318.452, 20.823]}
          rotation={[-Math.PI / 2, 0, -1.543]}
          scale={7.568}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane_Can_0.geometry}
          material={materials.material}
          position={[-64.246, 348.09, 20.74]}
          rotation={[-Math.PI / 2, 0, -1.543]}
          scale={7.568}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder006_Can_0.geometry}
          material={materials.material}
          position={[42.453, 214.198, 11.366]}
          rotation={[0, -0.88, 0.027]}
          scale={7.568}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane004_Can_0.geometry}
          material={materials.material}
          position={[19.566, 217.241, 30.196]}
          rotation={[0, -0.88, 0.027]}
          scale={7.568}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder004_Can_0.geometry}
          material={materials.material}
          position={[168.654, 191.948, 245.857]}
          rotation={[-Math.PI / 2, 0, -1.543]}
          scale={7.568}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001_Can_0.geometry}
          material={materials.material}
          position={[171.698, 221.586, 245.774]}
          rotation={[-Math.PI / 2, 0, -1.543]}
          scale={7.568}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder003_Can_0.geometry}
          material={materials.material}
          position={[169.619, 191.948, 312.673]}
          rotation={[-Math.PI / 2, 0, -2.767]}
          scale={7.568}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane002_Can_0.geometry}
          material={materials.material}
          position={[170.734, 221.586, 315.505]}
          rotation={[-Math.PI / 2, 0, -2.767]}
          scale={7.568}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/post_apo_fridge/scene.gltf')
